"""
QuestQA - a PDF question-answering bot built with Retrieval-Augmented Generation.

Pipeline (one function per stage):
    document_loader  ->  text_splitter  ->  watsonx_embedding  ->  vector_database
                     ->  retriever      ->  retriever_qa (RetrievalQA + LLM)  ->  Gradio UI

Credentials / endpoints are read from environment variables (see .env.example).
Inside the IBM Skills Network lab environment no API key is needed, so the code
falls back to the lab defaults (project_id="skills-network").
"""

import os
import warnings

import gradio as gr
from ibm_watsonx_ai import Credentials
from ibm_watsonx_ai.metanames import EmbedTextParamsMetaNames
from ibm_watsonx_ai.metanames import GenTextParamsMetaNames as GenParams
from langchain.chains import RetrievalQA
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.document_loaders import PyPDFLoader
from langchain_community.vectorstores import Chroma
from langchain_ibm import WatsonxEmbeddings, WatsonxLLM

try:  # optional: load a local .env file if python-dotenv is installed
    from dotenv import load_dotenv

    load_dotenv()
except ImportError:  # pragma: no cover
    pass

# You can use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass


warnings.warn = warn
warnings.filterwarnings("ignore")

# --------------------------------------------------------------------------- #
# Configuration
# --------------------------------------------------------------------------- #
WATSONX_URL = os.getenv("WATSONX_URL", "https://us-south.ml.cloud.ibm.com")
WATSONX_PROJECT_ID = os.getenv("WATSONX_PROJECT_ID", "skills-network")
WATSONX_APIKEY = os.getenv("WATSONX_APIKEY")  # not needed in the Skills Network lab

LLM_MODEL_ID = os.getenv("WATSONX_LLM_MODEL_ID", "ibm/granite-4-h-small")
EMBEDDING_MODEL_ID = os.getenv("WATSONX_EMBEDDING_MODEL_ID", "ibm/slate-125m-english-rtrvr-v2")


def _credentials():
    """Return watsonx credentials, adding the API key only when one is provided."""
    if WATSONX_APIKEY:
        return Credentials(url=WATSONX_URL, api_key=WATSONX_APIKEY)
    return Credentials(url=WATSONX_URL)


## LLM
def get_llm():
    model_id = LLM_MODEL_ID
    parameters = {
        GenParams.TEMPERATURE: 0.5,  # sampling temperature required by the lab
        GenParams.MAX_NEW_TOKENS: 256,  # maximum number of generated tokens
    }
    project_id = WATSONX_PROJECT_ID
    watsonx_llm = WatsonxLLM(
        model_id=model_id,
        url=WATSONX_URL,
        project_id=project_id,
        params=parameters,
        **({"apikey": WATSONX_APIKEY} if WATSONX_APIKEY else {}),
    )
    return watsonx_llm


## Document loader
def document_loader(file):
    # Gradio may hand us a tempfile-like object (has .name) or a plain file path string.
    path = getattr(file, "name", file)
    loader = PyPDFLoader(path)
    loaded_document = loader.load()
    return loaded_document


## Text splitter
def text_splitter(data):
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=50,
        length_function=len,
    )
    chunks = text_splitter.split_documents(data)
    return chunks


## Embedding model
def watsonx_embedding():
    embed_params = {
        EmbedTextParamsMetaNames.TRUNCATE_INPUT_TOKENS: 3,
        EmbedTextParamsMetaNames.RETURN_OPTIONS: {"input_text": True},
    }

    watsonx_embedding = WatsonxEmbeddings(
        model_id=EMBEDDING_MODEL_ID,
        url=WATSONX_URL,
        project_id=WATSONX_PROJECT_ID,
        params=embed_params,
        **({"apikey": WATSONX_APIKEY} if WATSONX_APIKEY else {}),
    )
    return watsonx_embedding


## Vector db
def vector_database(chunks):
    embedding_model = watsonx_embedding()
    vectordb = Chroma.from_documents(chunks, embedding_model)
    return vectordb


## Retriever
def retriever(file):
    splits = document_loader(file)
    chunks = text_splitter(splits)
    vectordb = vector_database(chunks)
    retriever = vectordb.as_retriever()  # default search_type="similarity"
    return retriever


## QA Chain
def retriever_qa(file, query):
    if file is None:
        return "Please upload a PDF file first."
    if not query or not query.strip():
        return "Please type a question about the document."

    llm = get_llm()
    retriever_obj = retriever(file)
    qa = RetrievalQA.from_chain_type(
        llm=llm,
        chain_type="stuff",
        retriever=retriever_obj,
        return_source_documents=False,
    )
    response = qa.invoke(query)
    return response["result"]


# Create Gradio interface
rag_application = gr.Interface(
    fn=retriever_qa,
    inputs=[
        gr.File(label="Upload PDF File", file_count="single", file_types=[".pdf"], type="filepath"),
        gr.Textbox(label="Input Query", lines=2, placeholder="Type your question here..."),
    ],
    outputs=gr.Textbox(label="Output"),
    title="Watsonx.ai RAG Chatbot",
    description=(
        "Upload a PDF document and ask any question. "
        "The chatbot will try to answer using the provided document."
    ),
)

# Launch the app
if __name__ == "__main__":
    rag_application.launch(server_name="0.0.0.0", server_port=7860)
